services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - Backend-Net

  backend:
    container_name: Backend
    image: hwnahee/backend:develop          # ― 변경 ―
    volumes:
      - static_volume:/Backend/static
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      SECRET_KEY: ${SECRET_KEY} # Django SECRET_KEY
      BITSTUDIO_API_KEY: ${BITSTUDIO_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_S3_CUSTOM_DOMAIN: ${AWS_S3_CUSTOM_DOMAIN}
      TNB_EMAIL: "${TNB_EMAIL}"
      TNB_PASSWORD: "${TNB_PASSWORD}"
      ENVIRONMENT: "prod"
      DEBUG: "False"
      SWAGGER_BASE_URL: "${SWAGGER_BASE_URL}"

    networks:
      - Backend-Net
    restart: always
    command: >
      sh -c "python wait_mysql.py &&
            python manage.py collectstatic --noinput &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 300"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=Backend-Net"
      # HTTP 라우터
      - "traefik.http.routers.backend-secure.rule=Host(`api.morphmall.shop`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.service=backend_service"
      - "traefik.http.services.backend_service.loadbalancer.server.port=8000"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.backend.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      # HTTPS 라우터
      - "traefik.http.routers.backend-secure.rule=Host(`api.morphmall.shop`)"
      - "traefik.http.routers.backend-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.routers.backend-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.backend-secure.service=backend_service"
    privileged: true

  traefik:
    image: traefik:v2.10
    container_name: Board-Traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker.network=Backend-Net"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=ymkim2353@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - Backend-Net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - backend
    restart: always
    tty: true
    expose:
      - 5672
    networks:
      - Backend-Net

  celery_worker:
    container_name: celery_worker
    image: hwnahee/backend:develop          # ― 변경 ―
    volumes:
      - ./:/app
    command: celery -A config worker --concurrency=4 --loglevel=info
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY} # Django SECRET_KEY
      BITSTUDIO_API_KEY: ${BITSTUDIO_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_S3_CUSTOM_DOMAIN: ${AWS_S3_CUSTOM_DOMAIN}
      TNB_EMAIL: "${TNB_EMAIL}"
      TNB_PASSWORD: "${TNB_PASSWORD}"
      ENVIRONMENT: "prod"
      DEBUG: "False"
      SWAGGER_BASE_URL: "${SWAGGER_BASE_URL}"
    depends_on:
      - rabbitmq
      - backend
    restart: always
    tty: true
    networks:
      - Backend-Net
    labels:
      - "traefik.enable=false"

  celery_beat:
    container_name: celery_beat
    image: hwnahee/backend:develop          # ― 변경 ―
    volumes:
      - ./:/app
    command: celery -A config beat --loglevel=info
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY} # Django SECRET_KEY
      BITSTUDIO_API_KEY: ${BITSTUDIO_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_S3_CUSTOM_DOMAIN: ${AWS_S3_CUSTOM_DOMAIN}
      TNB_EMAIL: "${TNB_EMAIL}"
      TNB_PASSWORD: "${TNB_PASSWORD}"
      ENVIRONMENT: "prod"
      DEBUG: "False"
      SWAGGER_BASE_URL: "${SWAGGER_BASE_URL}"
    depends_on:
      - rabbitmq
      - backend
    restart: always
    tty: true
    networks:
      - Backend-Net
    labels:
      - "traefik.enable=false"
  
  flower:
    image: mher/flower
    container_name: flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - TZ=Asia/Seoul
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery_worker
      - celery_beat
    networks:
      - Backend-Net
    labels:
      - "traefik.enable=false"

volumes:
  db_data:
  static_volume:
  letsencrypt:

networks:
  Backend-Net:
    driver: bridge
