global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs: #메트릭 수집 설정
      - targets: ['prometheus:9090']

  - job_name: 'backend'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['api.techeerfashion.shop']    # Traefik 도메인
    tls_config:
      insecure_skip_verify: true   # 자체 인증서라면
      
  - job_name: 'node-data'
    static_configs:
      - targets: ['node_exporter:9100']