name: Deploy Compose

on:
  repository_dispatch:
    types: [deploy-backend]
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # 코드 클론
        uses: actions/checkout@v4

      - name: Deploy the app # 배포중 메시지 출력
        run: echo "Deploying the app..."
      
      - name: Copy file to Server # docker-compose.yml파일을 서버로 복사
        id: copy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          source: |
            docker-compose.yml
            docker-compose.monitoring.yml
            prometheus/**
            grafana/**
          target: /home/ubuntu/
      
      - name: Deploy to Server # 복사된 docker-compose.yml 파일을 실행
        id: deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          script: |
            # ---- acme.json 권한 보장 ----
            sudo mkdir -p /home/ubuntu/letsencrypt
            sudo touch /home/ubuntu/letsencrypt/acme.json
            sudo chmod 600 /home/ubuntu/letsencrypt/acme.json
            # ----------------------------
            export DJANGO_SETTINGS_MODULE=config.settings.dev
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            export DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export DATABASE_USER=${{ secrets.DATABASE_USER }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}

            export SECRET_KEY="${{ secrets.SECRET_KEY }}"
            export BITSTUDIO_API_KEY=${{ secrets.BITSTUDIO_API_KEY }}
            export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            export AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }}
            export AWS_S3_CUSTOM_DOMAIN=${{ secrets.AWS_S3_CUSTOM_DOMAIN }}

            export TNB_EMAIL=${{ secrets.TNB_EMAIL }}
            export TNB_PASSWORD=${{ secrets.TNB_PASSWORD }}

            export SWAGGER_BASE_URL=${{ secrets.SWAGGER_BASE_URL }}

            docker compose \
            -f docker-compose.yml \
            -f docker-compose.monitoring.yml \
            down

            docker compose \
              -f docker-compose.yml \
              -f docker-compose.monitoring.yml \
              pull

            docker compose \
              -f docker-compose.yml \
              -f docker-compose.monitoring.yml \
              up -d --remove-orphans
      
      - name: Clean Up Files in Server # 이후 docker-compose.yml 파일 삭제
        if: always()
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -f /home/ubuntu/docker-compose.yml